// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Connection
{
    public partial class AddServices
    {
        public int Id { get; set; }
        public int? ProjectDetailsId { get; set; }
        public int? ServiceDescriptionId { get; set; }
        public decimal? Price { get; set; }

        public virtual ProjectDetails ProjectDetails { get; set; }
        public virtual ServiceDescription ServiceDescription { get; set; }
    }
}