// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Connection
{
    public partial class Customers
    {
        public Customers()
        {
            ProjectDetails = new HashSet<ProjectDetails>();
        }

        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }

        public virtual ICollection<ProjectDetails> ProjectDetails { get; set; }
    }
}