// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Connection
{
    public partial class ProjectDetails
    {
        public ProjectDetails()
        {
            AddServices = new HashSet<AddServices>();
        }

        public int Id { get; set; }
        public int? ClientsId { get; set; }
        public int? TypeOfReportId { get; set; }
        public string ProjectName { get; set; }
        public string Builder { get; set; }
        public string NoOfReferenceOrInvoice { get; set; }
        public string CleaningLocation { get; set; }
        public DateTime InsertedDate { get; set; }


        public virtual Customers Clients { get; set; }
        public virtual TypeOfReport TypeOfReport { get; set; }
        public virtual ICollection<AddServices> AddServices { get; set; }
    }
}