// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Connection
{
    public partial class Services
    {
        public Services()
        {
            ServiceDescription = new HashSet<ServiceDescription>();
        }

        public int Id { get; set; }
        public string ServiceName { get; set; }

        public virtual ICollection<ServiceDescription> ServiceDescription { get; set; }
    }
}