// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Connection
{
    public partial class ServiceDescription
    {
        public ServiceDescription()
        {
            AddServices = new HashSet<AddServices>();
        }

        public int Id { get; set; }
        public int? ServiceId { get; set; }
        public string Description { get; set; }

        public virtual Services Service { get; set; }
        public virtual ICollection<AddServices> AddServices { get; set; }
    }
}