// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Connection
{
    public partial class TypeOfReport
    {
        public TypeOfReport()
        {
            ProjectDetails = new HashSet<ProjectDetails>();
        }

        public int Id { get; set; }
        public string Type { get; set; }

        public virtual ICollection<ProjectDetails> ProjectDetails { get; set; }
    }
}